### ISSUE TITLE
Could you add support to fdopen (common used in some httpd)?

### ISSUE THREAD

**Issue by crackzhazha** [fkie-cad/libdesock#1]
I am really appreciate to this tool. But it doesn't  work when the web server use fdopen(sockfd,'r'), could you add support  to it.
I have upload the demo  server  which use  fdopen.
[minihttpd.zip](https://github.com/fkie-cad/libdesock/files/9594280/minihttpd.zip)
```
g++ minihttpd.c -o minihttpd
LD_PRELOAD='libdesock.so' ./minihttpd
```
And it will work abnormal

**Comment by pd-fkie** [comment]
Support for `fdopen` or `FILE*` functions in general will not be added because it is too much effort to implement the whole `stdio(3)` and `unlocked_stdio(3)` stack for such a small edge case.

Contributions that add this functionality to libdesock are of course welcome.
